server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://backendeureka:8761/eureka
  instance:
    hostname: backendgateway
    # prefer-ip-address: true
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      #   - AddResponseHeader=Access-Control-Allow-Origin, *
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
          add-to-simple-url-handler-mapping: true
          corsConfigurations:
            '[/**]':
              allowedOriginPatterns: "*"
              allowedHeaders: "*"
              allowCredentials: true
              allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: gestion-service
          uri: lb://gestion-service
          predicates:
            - Path=/telecom-cedia/api/gestion/**
          filters:
            - AuthenticationFilter
        - id: administracion-service
          uri: http://backenadministracion:8091
          predicates:
            - Path=/telecom-cedia/api/administracion/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: test-service-route
          uri: lb://gestion-service
          predicates:
            - Path=/test-service/v3/api-docs
            - Method=GET
        - id: administracion-service-route
          uri: http://backenadministracion:8091
          predicates:
            - Path=/telecom-cedia/api/administracion/test-service/v3/api-docs
            - Method=GET
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /test-service/v3/api-docs
        name: Test Service
      - url: /telecom-cedia/api/administracion/test-service/v3/api-docs
        name: Administracion Service